Repository kenzanlabs/capstan, pull requests merged in 2018-07, with the labels that each got.

#16 Use terraform to create spinnaker service account
  gcp/scripts/env.sh
  gcp/scripts/halyard_createSpinnaker.sh
  gcp/terraform/iam.tf
  gcp/terraform/instance.tf
  gcp/terraform/variables.tf
Labels: enhancement

#13 Feature: update contributing
  CONTRIBUTING.MD
Labels: Documentation

#17 GCP: Use single bucket created by terraform
  gcp/scripts/env.sh
  gcp/scripts/halyard_createSpinnaker.sh
  gcp/terraform/instance.tf
  gcp/terraform/storage.tf
  gcp/terraform/terraform.tfvars
  gcp/terraform/variables.tf
Labels: enhancement

#19 Add release notes
  gcp/RELEASE_NOTES.MD
Labels: Documentation, Next Release, Release Blocking

#18 Add GCP Pub Sub and Artifact repo
  gcp/scripts/create_GKE.sh
  gcp/scripts/enable_gpubsubartifact.sh
  gcp/scripts/env.sh
  gcp/scripts/halyard_createSpinnaker.sh
  gcp/scripts/instance_execute.sh
  gcp/terraform/iam.tf
  gcp/terraform/instance.tf
  gcp/terraform/pubsub.tf
Labels: Next Release, Release Blocking, enhancement

#23 Update GCP Process Image
  gcp/gcp_process.png
Labels: Documentation, Release Blocking

#22 Create 2018.q3.beta.gcp
  CONTRIBUTING.MD
  gcp/RELEASE_NOTES.MD
  gcp/gcp_process.png
  gcp/scripts/create_GKE.sh
  gcp/scripts/enable_gpubsubartifact.sh
  gcp/scripts/env.sh
  gcp/scripts/halyard_createSpinnaker.sh
  gcp/scripts/instance_execute.sh
  gcp/terraform/iam.tf
  gcp/terraform/instance.tf
  gcp/terraform/pubsub.tf
  gcp/terraform/storage.tf
  gcp/terraform/terraform.tfvars
  gcp/terraform/variables.tf
Labels: Next Release
