Repository kenzanlabs/capstan, pull requests merged in 2019-08, with the labels that each got.

#55 Feature/gcp refresh
  gcp/README.md
  gcp/RELEASE_NOTES.MD
  gcp/scripts/halyard_createSpinnaker.sh
  gcp/scripts/instance_execute.sh
  gcp/terraform/iam.tf
  gcp/terraform/instance.tf
  jenkins.md
  pipelines/gcp/0-initial/README.md
  pipelines/gcp/0-initial/dev-loadbalancer.yaml
  pipelines/gcp/1-pubsubWpodscaling/README.md
  pipelines/gcp/2-canary/canary_prod.json
Labels: Documentation, Maintenance, enhancement

#56 merge in minor changes from feature/oss2019
  gcp/terraform/instance.tf
Labels: enhancement

#57 update pipelines to not use deployments
  pipelines/gcp/0-initial/prod_seed.json
  pipelines/gcp/0-initial/uat_deploy.json
  pipelines/gcp/1-pubsubWpodscaling/dev-pipeline.sed.json
Labels: enhancement

#58 Clarify some sections
  pipelines/gcp/0-initial/README.md
  pipelines/gcp/1-pubsubWpodscaling/README.md
  pipelines/gcp/1-pubsubWpodscaling/enable_cloud_build_api.png
Labels: Documentation

#60 Minor fixes to canary section
  pipelines/gcp/2-canary/README.md
Labels: Documentation

#61 Feature/process png
  gcp/README.md
  gcp/gcp_process.png
Labels: Documentation

#62 force an explicit dependency
  gcp/terraform/instance.tf
  gcp/terraform/terraform.tfvars
  gcp/terraform/variables.tf
Labels: Documentation, enhancement

#63 Create Maintenance Release q3 2019
  gcp/README.md
  gcp/RELEASE_NOTES.MD
  gcp/gcp_process.png
  gcp/scripts/halyard_createSpinnaker.sh
  gcp/scripts/instance_execute.sh
  gcp/terraform/iam.tf
  gcp/terraform/instance.tf
  gcp/terraform/terraform.tfvars
  gcp/terraform/variables.tf
  jenkins.md
  pipelines/gcp/0-initial/README.md
  pipelines/gcp/0-initial/dev-loadbalancer.yaml
  pipelines/gcp/0-initial/prod_seed.json
  pipelines/gcp/0-initial/uat_deploy.json
  pipelines/gcp/1-pubsubWpodscaling/README.md
  pipelines/gcp/1-pubsubWpodscaling/dev-pipeline.sed.json
  pipelines/gcp/1-pubsubWpodscaling/enable_cloud_build_api.png
  pipelines/gcp/2-canary/README.md
  pipelines/gcp/2-canary/canary_prod.json
Labels: Documentation, Next Release, bug, enhancement
